# infra-base 页面静态资源
location /home_page/ {
  alias /etc/nginx/www/home_page/;
}

# Minio
location /minio/ {
  proxy_pass http://minio:9000/;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  proxy_buffering off;
}

# 网关API
location /gateway-api/ {
  proxy_pass https://www.baidu.com/;
  proxy_set_header X-Forwarded-For $remote_addr;  # 客户端真实 IP
  proxy_set_header X-Forwarded-Proto $scheme;     # 请求协议（http 或 https）
  proxy_set_header X-Real-IP $remote_addr;        # 真实客户端 IP（可选）
  proxy_set_header X-Forwarded-Port $server_port; # 真实客户端端口
  proxy_set_header Host $host;                    # 保持原始 Host 头
}
