user root;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    # access_log  logs/access.log  main;

    resolver 127.0.0.11 valid=30s;

    server_tokens off;  # 禁用版本信息

    sendfile on;
    
    keepalive_timeout 65;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 32 4k;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/xml text/javascript image/jpeg image/gif image/png application/javascript application/vnd.ms-fontobject font/x-woff image/svg+xml application/octet-stream application/json;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    client_max_body_size 200m;
    
    # map   {
    #     default upgrade;
    #     '' close;
    # }

    server {
        #listen 443 ssl;
        listen 80;
        #server_name www.baidu.com;
        #ssl_certificate /etc/di-center/base_hub/nginx/cert/www.baidu.com.pem;
        #ssl_certificate_key /etc/di-center/base_hub/nginx/cert/www.baidu.com.key;

        include /etc/nginx/location.conf;
    }

}
